ALTER TABLE sets ADD COLUMN price_guide VARCHAR(100) DEFAULT '';

UPDATE sets SET price_guide = '10th Edition' WHERE id = '10E';   
UPDATE sets SET price_guide = 'Unlimited Edition' WHERE id = '2ED';
UPDATE sets SET price_guide = 'Revised Edition' WHERE id = '3ED';
UPDATE sets SET price_guide = 'Fouth Edition' WHERE id = '4ED';
UPDATE sets SET price_guide = 'Fifth Dawn' WHERE id = '5DN';
UPDATE sets SET price_guide = 'Fifth Edition' WHERE id = '5ED';
UPDATE sets SET price_guide = 'Classic Sixth Edition' WHERE id = '6ED';
UPDATE sets SET price_guide = '7th Edition' WHERE id = '7ED';
UPDATE sets SET price_guide = '8th Edition' WHERE id = '8BS';
UPDATE sets SET price_guide = '8th Edition' WHERE id = '8ED';
UPDATE sets SET price_guide = '9th Edition' WHERE id = '9BS';
UPDATE sets SET price_guide = '9th Edition' WHERE id = '9ED';
UPDATE sets SET price_guide = 'Shards of Alara' WHERE id = 'ALA';
UPDATE sets SET price_guide = 'Alliances' WHERE id = 'ALL';
UPDATE sets SET price_guide = 'Apocalypse' WHERE id = 'APC';
UPDATE sets SET price_guide = 'Alara Reborn' WHERE id = 'ARB';
UPDATE sets SET price_guide = 'Archenemy' WHERE id = 'ARC';
UPDATE sets SET price_guide = 'Arabian Nights' WHERE id = 'ARN';
UPDATE sets SET price_guide = 'Anthologies' WHERE id = 'ATH';
UPDATE sets SET price_guide = 'Antiquities' WHERE id = 'ATQ';
UPDATE sets SET price_guide = 'Avacyn Restored' WHERE id = 'AVR';
UPDATE sets SET price_guide = 'Born of the Gods' WHERE id = 'BNG';
UPDATE sets SET price_guide = 'Betrayers of Kamigawa' WHERE id = 'BOK';
UPDATE sets SET price_guide = 'Battle Royale Box Set' WHERE id = 'BRB';
UPDATE sets SET price_guide = 'Beatdown Box Set' WHERE id = 'BTD';
UPDATE sets SET price_guide = 'Commander 2013' WHERE id = 'C13';
UPDATE sets SET price_guide = 'Commander 2014' WHERE id = 'C14';
UPDATE sets SET price_guide = 'Champions of Kamigawa' WHERE id = 'CHK';
UPDATE sets SET price_guide = 'Chronicles' WHERE id = 'CHR';
UPDATE sets SET price_guide = 'Commander''s Arsenal' WHERE id = 'CM1';
UPDATE sets SET price_guide = 'Commander' WHERE id = 'CMD';
UPDATE sets SET price_guide = 'Conspiracy' WHERE id = 'CNS';
UPDATE sets SET price_guide = 'Conflux' WHERE id = 'CON';
UPDATE sets SET price_guide = 'Coldsnap' WHERE id = 'CSP';
UPDATE sets SET price_guide = 'Coldsnap Theme Deck Reprints' WHERE id = 'CST';
UPDATE sets SET price_guide = 'Duel Decks: Jace vs. Chandra' WHERE id = 'DD2';
UPDATE sets SET price_guide = 'Duel Decks: Divine vs. Demonic' WHERE id = 'DDC';
UPDATE sets SET price_guide = 'Duel Decks: Garruk vs. Liliana' WHERE id = 'DDD';
UPDATE sets SET price_guide = 'Duel Decks: Phyrexia vs. the Coalition' WHERE id = 'DDE';
UPDATE sets SET price_guide = 'Duel Decks: Elspeth vs. Tezzeret' WHERE id = 'DDF';
UPDATE sets SET price_guide = 'Duel Decks: Knights vs Dragons' WHERE id = 'DDG';
UPDATE sets SET price_guide = 'Duel Decks: Ajani vs. Nicol Bolas' WHERE id = 'DDH';
UPDATE sets SET price_guide = 'Duel Decks: Venser vs. Koth' WHERE id = 'DDI';
UPDATE sets SET price_guide = 'Duel Decks: Izzet vs. Golgari' WHERE id = 'DDJ';
UPDATE sets SET price_guide = 'Duel Decks: Sorin vs. Tibalt' WHERE id = 'DDK';
UPDATE sets SET price_guide = 'Duel Decks: Heroes vs. Monsters' WHERE id = 'DDL';
UPDATE sets SET price_guide = 'Duel Decks: Jace vs Vraska' WHERE id = 'DDM';
UPDATE sets SET price_guide = 'Duel Decks: Speed vs Cunning' WHERE id = 'DDN';
UPDATE sets SET price_guide = 'Dragon''s Maze' WHERE id = 'DGM';
UPDATE sets SET price_guide = 'Dissension' WHERE id = 'DIS';
UPDATE sets SET price_guide = 'Dark Ascension' WHERE id = 'DKA';
UPDATE sets SET price_guide = 'Deckmasters Garfield vs. Finkel' WHERE id = 'DKM';
UPDATE sets SET price_guide = 'Duels of the Planeswalkers' WHERE id = 'DPA';
UPDATE sets SET price_guide = 'From the Vault: Dragons' WHERE id = 'DRB';
UPDATE sets SET price_guide = 'The Dark' WHERE id = 'DRK';
UPDATE sets SET price_guide = 'Darksteel' WHERE id = 'DST';
UPDATE sets SET price_guide = 'Eventide' WHERE id = 'EVE';
UPDATE sets SET price_guide = 'Duel Decks: Elves vs. Goblins' WHERE id = 'EVG';
UPDATE sets SET price_guide = 'Exodus' WHERE id = 'EXO';
UPDATE sets SET price_guide = 'Fallen Empires' WHERE id = 'FEM';
UPDATE sets SET price_guide = 'Future Sight' WHERE id = 'FUT';
UPDATE sets SET price_guide = 'Guildpact' WHERE id = 'GPT';
UPDATE sets SET price_guide = 'Gatecrash' WHERE id = 'GTC';
UPDATE sets SET price_guide = 'Premium Deck Series: Slivers' WHERE id = 'H09';
UPDATE sets SET price_guide = 'Homelands' WHERE id = 'HML';
UPDATE sets SET price_guide = 'Planechase' WHERE id = 'HOP';
UPDATE sets SET price_guide = 'Ice Age' WHERE id = 'ICE';
UPDATE sets SET price_guide = 'Invasion' WHERE id = 'INV';
UPDATE sets SET price_guide = 'Innistrad' WHERE id = 'ISD';
UPDATE sets SET price_guide = 'Journey into Nyx' WHERE id = 'JOU';
UPDATE sets SET price_guide = 'Judgment' WHERE id = 'JUD';
UPDATE sets SET price_guide = 'Khans of Tarkir' WHERE id = 'KTK';
UPDATE sets SET price_guide = 'Alpha Edition' WHERE id = 'LEA';
UPDATE sets SET price_guide = 'Beta Edition' WHERE id = 'LEB';
UPDATE sets SET price_guide = 'Legends' WHERE id = 'LEG';
UPDATE sets SET price_guide = 'Legions' WHERE id = 'LGN';
UPDATE sets SET price_guide = 'Lorwyn' WHERE id = 'LRW';
UPDATE sets SET price_guide = 'Magic 2010 (M10)' WHERE id = 'M10';
UPDATE sets SET price_guide = 'Magic 2011 (M11)' WHERE id = 'M11';
UPDATE sets SET price_guide = 'Magic 2012 (M12)' WHERE id = 'M12';
UPDATE sets SET price_guide = 'Magic 2013 (M13)' WHERE id = 'M13';
UPDATE sets SET price_guide = 'Magic 2014 (M14)' WHERE id = 'M14';
UPDATE sets SET price_guide = 'Magic 2015 (M15)' WHERE id = 'M15';
UPDATE sets SET price_guide = 'Mirrodin Besieged' WHERE id = 'MBS';
UPDATE sets SET price_guide = 'Magic Modern Event Deck' WHERE id = 'MD1';
UPDATE sets SET price_guide = 'Mirage' WHERE id = 'MIR';
UPDATE sets SET price_guide = 'Modern Masters' WHERE id = 'MMA';
UPDATE sets SET price_guide = 'Mercadian Masques' WHERE id = 'MMQ';
UPDATE sets SET price_guide = 'Morningtide' WHERE id = 'MOR';
UPDATE sets SET price_guide = 'Mirrodin' WHERE id = 'MRD';
UPDATE sets SET price_guide = 'Nemesis' WHERE id = 'NMS';
UPDATE sets SET price_guide = 'New Phyrexia' WHERE id = 'NPH';
UPDATE sets SET price_guide = 'Odyssey' WHERE id = 'ODY';
UPDATE sets SET price_guide = 'Onslaught' WHERE id = 'ONS';
UPDATE sets SET price_guide = 'Planechase 2012' WHERE id = 'PC2';
UPDATE sets SET price_guide = 'Prophecy' WHERE id = 'PCY';
UPDATE sets SET price_guide = 'Premium Deck Series: Fire and Lightning' WHERE id = 'PD2';
UPDATE sets SET price_guide = 'Premium Deck Series: Graveborn' WHERE id = 'PD3';
UPDATE sets SET price_guide = 'Planar Chaos' WHERE id = 'PLC';
UPDATE sets SET price_guide = 'Planeshift' WHERE id = 'PLS';
UPDATE sets SET price_guide = 'Portal Second Age' WHERE id = 'PO2';
UPDATE sets SET price_guide = 'Portal' WHERE id = 'POR';
UPDATE sets SET price_guide = 'Portal Three Kingdoms' WHERE id = 'PTK';
UPDATE sets SET price_guide = 'Ravnica' WHERE id = 'RAV';
UPDATE sets SET price_guide = 'Rise of the Eldrazi' WHERE id = 'ROE';
UPDATE sets SET price_guide = 'Fouth Edition' WHERE id = 'RQS';
UPDATE sets SET price_guide = 'Return to Ravnica' WHERE id = 'RTR';
UPDATE sets SET price_guide = 'Starter 2000' WHERE id = 'S00';
UPDATE sets SET price_guide = 'Starter 1999' WHERE id = 'S99';
UPDATE sets SET price_guide = 'Scourge' WHERE id = 'SCG';
UPDATE sets SET price_guide = 'Shadowmoor' WHERE id = 'SHM';
UPDATE sets SET price_guide = 'Saviors of Kamigawa' WHERE id = 'SOK';
UPDATE sets SET price_guide = 'Scars of Mirrodin' WHERE id = 'SOM';
UPDATE sets SET price_guide = 'Stronghold' WHERE id = 'STH';
UPDATE sets SET price_guide = 'Theros' WHERE id = 'THS';
UPDATE sets SET price_guide = 'Tempest' WHERE id = 'TMP';
UPDATE sets SET price_guide = 'Torment' WHERE id = 'TOR';
UPDATE sets SET price_guide = 'Timeshifted' WHERE id = 'TSB';
UPDATE sets SET price_guide = 'Time Spiral' WHERE id = 'TSP';
UPDATE sets SET price_guide = 'Urza''s Destiny' WHERE id = 'UDS';
UPDATE sets SET price_guide = 'Unglued' WHERE id = 'UGL';
UPDATE sets SET price_guide = 'Urza''s Legacy' WHERE id = 'ULG';
UPDATE sets SET price_guide = 'Unhinged' WHERE id = 'UNH';
UPDATE sets SET price_guide = 'Urza''s Saga' WHERE id = 'USG';
UPDATE sets SET price_guide = 'From the Vault: Exiled' WHERE id = 'V09';
UPDATE sets SET price_guide = 'From the Vault: Relics' WHERE id = 'V10';
UPDATE sets SET price_guide = 'From the Vault: Legends' WHERE id = 'V11';
UPDATE sets SET price_guide = 'From the Vault: Realms' WHERE id = 'V12';
UPDATE sets SET price_guide = 'From the Vault: Twenty' WHERE id = 'V13';
UPDATE sets SET price_guide = 'From the Vault: Annihilation' WHERE id = 'V14';
UPDATE sets SET price_guide = 'Vanguard' WHERE id = 'VAN';
UPDATE sets SET price_guide = 'Visions' WHERE id = 'VIS';
UPDATE sets SET price_guide = 'Weatherlight' WHERE id = 'WTH';
UPDATE sets SET price_guide = 'Worldwake' WHERE id = 'WWK';
UPDATE sets SET price_guide = 'Zendikar' WHERE id = 'ZEN';
UPDATE sets SET price_guide = 'Pro Tour Promos' WHERE id = 'p15A';
UPDATE sets SET price_guide = 'Arena Promos' WHERE id = 'p2HG';
UPDATE sets SET price_guide = 'APAC Lands' WHERE id = 'pALP';
UPDATE sets SET price_guide = 'Arena Promos' WHERE id = 'pARL';
UPDATE sets SET price_guide = 'Special Occasion' WHERE id = 'pCEL';
UPDATE sets SET price_guide = 'Champs Promos' WHERE id = 'pCMP';
UPDATE sets SET price_guide = 'Media Promos' WHERE id = 'pDRC';
UPDATE sets SET price_guide = 'European Lands' WHERE id = 'pELP';
UPDATE sets SET price_guide = 'FNM Promos' WHERE id = 'pFNM';
UPDATE sets SET price_guide = 'Grand Prix Promos' WHERE id = 'pGPX';
UPDATE sets SET price_guide = 'Guru Lands' WHERE id = 'pGRU';
UPDATE sets SET price_guide = 'Special Occasion' WHERE id = 'pHHO';
UPDATE sets SET price_guide = 'Judge Promos' WHERE id = 'pJGP';
UPDATE sets SET price_guide = 'Arena Promos' WHERE id = 'pLGM';
UPDATE sets SET price_guide = 'Launch Party Cards' WHERE id = 'pLPA';
UPDATE sets SET price_guide = 'Media Promos' WHERE id = 'pMEI';
UPDATE sets SET price_guide = 'Game Day Promos' WHERE id = 'pMGD';
UPDATE sets SET price_guide = 'Magic Player Rewards' WHERE id = 'pMPR';
UPDATE sets SET price_guide = 'Prerelease Cards' WHERE id = 'pPRE';
UPDATE sets SET price_guide = 'Pro Tour Promos' WHERE id = 'pPRO';
UPDATE sets SET price_guide = 'Release Event Cards' WHERE id = 'pREL';
UPDATE sets SET price_guide = 'Gateway Promos' WHERE id = 'pSUM';
UPDATE sets SET price_guide = 'JSS/MSS Promos' WHERE id = 'pSUS';
UPDATE sets SET price_guide = 'WPN Promos' WHERE id = 'pWCQ';
UPDATE sets SET price_guide = 'Judge Promos' WHERE id = 'pWOR';
UPDATE sets SET price_guide = 'Unique and Miscellaneous Promos' WHERE id = 'pWOS';
UPDATE sets SET price_guide = 'Gateway Promos' WHERE id = 'pWPNj';
UPDATE sets SET price_guide = 'Gateway Promos' WHERE id = 'pWPN';

ALTER TABLE sets ADD COLUMN priced boolean DEFAULT true;

UPDATE sets SET priced = false WHERE id = 'ITP';
UPDATE sets SET priced = false WHERE id = 'MED'; -- online only
UPDATE sets SET priced = false WHERE id = 'ME2'; -- online only
UPDATE sets SET priced = false WHERE id = 'ME3'; -- online only
UPDATE sets SET priced = false WHERE id = 'ME4'; -- online only
UPDATE sets SET priced = false WHERE id = 'MGB';
UPDATE sets SET priced = false WHERE id = 'VMA'; -- online only
UPDATE sets SET priced = false WHERE id = 'pPOD';

